name: vlang-build-pipeline

on:
  push:
    paths-ignore:
      - "**.md"
      - ".editorconfig"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: latest
        id: v
      - name: Build repository app
        run: v -prod ngc.v -o ngc -os linux
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Production Build for Linux"
          files: |
            ngc
